##########################################################
###################  开发环境的profile  ###################
##########################################################
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/guns_flowable?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: root
    db-name: guns
    filters: log4j,wall,mergeStat

#flowable数据源和多数据源配置
#guns:
  #flowable:
    #datasource:
      #url: jdbc:mysql://127.0.0.1:3306/guns_flowable?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
      #username: root
      #password: root
  #muti-datasource:
    #default-dataSource-name: dataSourceGuns #默认的数据源名称
    #url: jdbc:mysql://127.0.0.1:3306/guns_flowable?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    #username: root
    #password: root

logging:
  level.root: info
  level.com.stylefeng: debug
  path: logs/
  file: guns.log
  
debug: false